- name: Add Hashicorp Stable APT repository
  deb822_repository:
    name: hashicorp
    types: [deb]
    uris: "https://apt.releases.hashicorp.com"
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [main]
    state: present
    enabled: yes
  notify: Update cache

- meta: flush_handlers

- name: Install Packer
  package:
    state: latest
    name:
      - packer
  when: ansible_distribution in ["Debian", "Ubuntu"]
