- name: Upgrade apt packages on (Ubuntu, Debian)
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]
